# Generated by Django 4.2.7 on 2023-12-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_slug_room_tag_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
    ]
