# Generated by Django 4.2.7 on 2023-12-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_users_room_follower_rename_user_room_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='follower',
            new_name='followers',
        ),
    ]
