# Generated by Django 4.2.7 on 2023-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_follower_room_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.TextField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
