# Generated by Django 4.2.7 on 2023-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_image_alter_room_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.TextField(max_length=2000000),
        ),
    ]
