# Generated by Django 4.2.7 on 2023-12-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
