# Generated by Django 4.2.7 on 2023-12-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='room_id',
            new_name='room',
        ),
    ]
