# Generated by Django 4.2.7 on 2023-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_user_id_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Opción 1'), (2, 'Opción 2')], default=0),
        ),
    ]
